// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "modelConfigMode": string;
      "apiConfigMode": string;
      "provider": string;
      "api": string;
      "secretKey": string;
      "embeddingModel": string;
      "embeddingBatchNum": number;
      "temperature": number;
      "apiBaseURL": string;
      "apiKey": string;
      "model": string;
      "timeoutSeconds": number;
      "dailyLimit": number;
      "usePDFAsInputSource": boolean;
      "usePDFAnnotationsAsContext": boolean;
      "importPDFAnnotationsAsField": boolean;
      "customPromptTemplate": string;
      "customFolderSummaryPromptTemplate": string;
    };
  }
}
